/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <bool.h>

/* Define Clock Source */
#define PERIPH_BASE 0x40000000UL
#define APB1PERIPH_BASE PERIPH_BASE
#define AHB1PERIPH_BASE (PERIPH_BASE + 0x00020000UL)

#define RCC_BASE_ADDR (AHB1PERIPH_BASE + 0x3800UL)

#define RCC_CFGR_OFFSET	0x08UL
#define RCC_CR_OFFSET	0x00UL

#define RCC_CFGR_REG_ADDR (RCC_BASE_ADDR + RCC_CFGR_OFFSET)
#define RCC_CR_REG_ADDR	(RCC_BASE_ADDR + RCC_CR_OFFSET)

/* Define Peripheral Source*/
#define RCC_AHB1ENR_ADDR (RCC_BASE_ADDR + 0x30UL)
#define GPIOA_BASE_ADDR (AHB1PERIPH_BASE + 0x00UL)
#define GPIOB_BASE_ADDR (AHB1PERIPH_BASE + 0x400UL)
#define GPIOC_BASE_ADDR (AHB1PERIPH_BASE + 0x800UL)


/* Pointer to REG */
uint32_t *pRccCfgrReg = (uint32_t *) RCC_CFGR_REG_ADDR;
uint32_t *pRccCrReg = (uint32_t *) RCC_CR_REG_ADDR;

uint32_t *pRccAhb1enr = (uint32_t *) RCC_AHB1ENR_ADDR;

/* Struct RCC, PA, PC */
typedef struct {
	volatile uint32_t CR;
	uint32_t RV1[11];
	volatile uint32_t AHB1;
	volatile uint32_t AHB2;
	uint32_t RV2[2];
	volatile uint32_t APB1;
	volatile uint32_t APB2;
}RCC_OFF;

typedef struct{
	uint32_t MODE;
	uint32_t TYPE;
	uint32_t SPEED;
	uint32_t PULL;
}GPIOx_REG;

#define RCC ((RCC_OFF *) RCC_BASE_ADDR)
#define PA	((GPIOx_REG *) GPIOA_BASE_ADDR)
#define PB  ((GPIOx_REG *) GPIOB_BASE_ADDR)
#define PC	((GPIOx_REG *) GPIOC_BASE_ADDR)
#define PD  ((GPIOx_REG *) GPIOD_BASE_ADDR)

int main(void)
{
	/* HSEON = 1 */
	*pRccCrReg |= (1 << 16);
	while(! (*pRccCrReg & (1 << 17)));

	/* HSE as System Clock */
	*pRccCfgrReg |= (1 << 0);
	/* Enable Clock config for GPIOA,C */
	*pRccAhb1enr |= ((1 << 2) | (1 << 0));
	//RCC->AHB1 |= (1 << 0) | (1 << 2);


    /* Loop forever */
	while(1)
	{

	}

}
